services:
  database:
    image: postgres:15.7
    container_name: caseinterview_database
    ports:
      - "5499:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc
      - POSTGRES_DB=caseinterview

  app:
    image: pyramid-app-caseinterview
    build:
      context: .
      args:
        CONTAINER_REGISTRY: ${CONTAINER_REGISTRY}
        PIP_ACCESS_TOKEN: ${PIP_ACCESS_TOKEN}
    container_name: caseinterview_app
    environment:
      - PG_PASSWORD=abc
      - PG_USER=postgres
      - PG_DBNAME=caseinterview
      - PG_PORT=5432
      - PG_HOST=database
      - ACCOUNTS_TOKEN_SECRET=mysecret
    depends_on: 
      - "database"
    ports:
      - "6599:6543"
      - "8888:8888"
    tty: true

  collector-alloy:
    image: grafana/alloy:latest
    container_name: collector-alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - --config.format=alloy
      - --stability.level=experimental
      - /etc/alloy/config.alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP (optional)
      - "12345:12345" # Alloy Admin UI
    depends_on: 
      - "app"